alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Class_Student drop constraint FKhcxqus7alhtujwkt9vrskl96u
alter table Class_Student drop constraint FKiyrdd7o3adlxvqvasphgo0jsh
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Class_Student cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Class_Student drop constraint FKhcxqus7alhtujwkt9vrskl96u
alter table Class_Student drop constraint FKiyrdd7o3adlxvqvasphgo0jsh
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Class_Student cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
